In [57]:
import numpy as np

# Задание 1


In [58]:
n = 17
a = np.arange(0, n+1)
a[::-1]

array([17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,
        0])

# Задание 2

In [59]:
n = 15
a = np.diag(np.arange(0, n+1), k=0)
a

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  5,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  7,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  8,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  9,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 11,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 12,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,

In [60]:
np.sum(a)

120

# Задание 3

In [61]:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

SyntaxError: invalid syntax (<ipython-input-61-3f93580d4b36>, line 1)

In [62]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )

In [63]:
b = np.array( [4, 12, -3] )

In [64]:
from numpy import linalg
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [65]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

# Задание 4

In [66]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [67]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [68]:
next_user_statsLength = np.linalg.norm( next_user_stats )
next_user_statsLength

2.23606797749979

In [69]:
for i in users_stats:
    iLength = np.linalg.norm( i )
    z = np.dot( i, next_user_stats ) / ( iLength * next_user_statsLength )
    print(z)

0.19999999999999996
0.8451542547285165
0.3999999999999999
0.7905694150420948
0.3999999999999999
0.0
0.0
0.9486832980505138
0.0
0.0


In [70]:
# не совсем понимаю как правильно отобразить что максимальное сходство наблюдается с пользователем номер 8, буду благодарен за подсказку